/* Generated By:JavaCC: Do not edit this line. MdCompatibleParserTreeConstants.java Version 5.0 */
package pictures.reisishot.velocity.runtime.parser.custom.node;

public interface MdCompatibleParserTreeConstants {
    int JJTPROCESS = 0;
    int JJTVOID = 1;
    int JJTTEXT = 2;
    int JJTESCAPEDDIRECTIVE = 3;
    int JJTESCAPE = 4;
    int JJTCOMMENT = 5;
    int JJTTEXTBLOCK = 6;
    int JJTFLOATINGPOINTLITERAL = 7;
    int JJTINTEGERLITERAL = 8;
    int JJTSTRINGLITERAL = 9;
    int JJTIDENTIFIER = 10;
    int JJTWORD = 11;
    int JJTDIRECTIVEASSIGN = 12;
    int JJTDIRECTIVE = 13;
    int JJTBLOCK = 14;
    int JJTMAP = 15;
    int JJTOBJECTARRAY = 16;
    int JJTINTEGERRANGE = 17;
    int JJTMETHOD = 18;
    int JJTINDEX = 19;
    int JJTREFERENCE = 20;
    int JJTTRUE = 21;
    int JJTFALSE = 22;
    int JJTIFSTATEMENT = 23;
    int JJTELSESTATEMENT = 24;
    int JJTELSEIFSTATEMENT = 25;
    int JJTSETDIRECTIVE = 26;
    int JJTEXPRESSION = 27;
    int JJTASSIGNMENT = 28;
    int JJTORNODE = 29;
    int JJTANDNODE = 30;
    int JJTEQNODE = 31;
    int JJTNENODE = 32;
    int JJTLTNODE = 33;
    int JJTGTNODE = 34;
    int JJTLENODE = 35;
    int JJTGENODE = 36;
    int JJTADDNODE = 37;
    int JJTSUBTRACTNODE = 38;
    int JJTMULNODE = 39;
    int JJTDIVNODE = 40;
    int JJTMODNODE = 41;
    int JJTNOTNODE = 42;
    int JJTNEGATENODE = 43;


    String[] jjtNodeName = {
            "process",
            "void",
            "Text",
            "EscapedDirective",
            "Escape",
            "Comment",
            "Textblock",
            "FloatingPointLiteral",
            "IntegerLiteral",
            "StringLiteral",
            "Identifier",
            "Word",
            "DirectiveAssign",
            "Directive",
            "Block",
            "Map",
            "ObjectArray",
            "IntegerRange",
            "Method",
            "Index",
            "Reference",
            "True",
            "False",
            "IfStatement",
            "ElseStatement",
            "ElseIfStatement",
            "SetDirective",
            "Expression",
            "Assignment",
            "OrNode",
            "AndNode",
            "EQNode",
            "NENode",
            "LTNode",
            "GTNode",
            "LENode",
            "GENode",
            "AddNode",
            "SubtractNode",
            "MulNode",
            "DivNode",
            "ModNode",
            "NotNode",
            "NegateNode",
    };
}
/* JavaCC - OriginalChecksum=cf71de538eda695a35ddac945823b5f5 (do not edit this line) */
