/* Generated By:JavaCC: Do not edit this line. MdCompatibleParserVisitor.java Version 5.0 */
package pictures.reisishot.velocity.runtime.parser.custom.node;

import org.apache.velocity.runtime.parser.node.*;

public interface MdCompatibleParserVisitor {
    Object visit(SimpleNode node, Object data);

    Object visit(ASTprocess node, Object data);

    Object visit(ASTText node, Object data);

    Object visit(ASTEscapedDirective node, Object data);

    Object visit(ASTEscape node, Object data);

    Object visit(ASTComment node, Object data);

    Object visit(ASTTextblock node, Object data);

    Object visit(ASTFloatingPointLiteral node, Object data);

    Object visit(ASTIntegerLiteral node, Object data);

    Object visit(ASTStringLiteral node, Object data);

    Object visit(ASTIdentifier node, Object data);

    Object visit(ASTWord node, Object data);

    Object visit(ASTDirectiveAssign node, Object data);

    Object visit(ASTDirective node, Object data);

    Object visit(ASTBlock node, Object data);

    Object visit(ASTMap node, Object data);

    Object visit(ASTObjectArray node, Object data);

    Object visit(ASTIntegerRange node, Object data);

    Object visit(ASTMethod node, Object data);

    Object visit(ASTIndex node, Object data);

    Object visit(ASTReference node, Object data);

    Object visit(ASTTrue node, Object data);

    Object visit(ASTFalse node, Object data);

    Object visit(ASTIfStatement node, Object data);

    Object visit(ASTElseStatement node, Object data);

    Object visit(ASTElseIfStatement node, Object data);

    Object visit(ASTSetDirective node, Object data);

    Object visit(ASTExpression node, Object data);

    Object visit(ASTAssignment node, Object data);

    Object visit(ASTOrNode node, Object data);

    Object visit(ASTAndNode node, Object data);

    Object visit(ASTEQNode node, Object data);

    Object visit(ASTNENode node, Object data);

    Object visit(ASTLTNode node, Object data);

    Object visit(ASTGTNode node, Object data);

    Object visit(ASTLENode node, Object data);

    Object visit(ASTGENode node, Object data);

    Object visit(ASTAddNode node, Object data);

    Object visit(ASTSubtractNode node, Object data);

    Object visit(ASTMulNode node, Object data);

    Object visit(ASTDivNode node, Object data);

    Object visit(ASTModNode node, Object data);

    Object visit(ASTNotNode node, Object data);

    Object visit(ASTNegateNode node, Object data);
}
/* JavaCC - OriginalChecksum=7e49ba94d6c4ccf5197ed9c2bec92536 (do not edit this line) */
