name: Build on master with Sonar
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Change wrapper permission
        run: chmod +x ./gradlew
      - name: 🔦 Test
        run: ./gradlew test --parallel --build-cache
      - name: ✉ Create aggregated report
        run: ./gradlew jacocoAggregatedReport -x test --parallel
      - uses: codecov/codecov-action@v2
        name: 🔍 Codecov report
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          files: ./build/reports/jacoco/jacocoAggregatedReport/jacocoAggregatedReport.xml
          fail_ci_if_error: true
      - name: 🔍 Sonarqube report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonarqube -x test --parallel
      - name: Stop Gradle
        run: ./gradlew --stop
